name: CI Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Adjust Java version as needed

    - name: Build and test with Maven
      run: mvn clean test
    - name: Run tests with TestNG
      run: mvn test -Dtest=TestNGTestClass

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports  # Adjust path to TestNG reports

    - name: Publish test results
      if: always()
      uses: actions/checkout@v2
      with:
        path: target/surefire-reports
